echo enableCORS = false >> ~/.streamlit/config.toml
echo enableXsrfProtection = false >> ~/.streamlit/config.toml
echo enableWebsocketCompression = false >> ~/.streamlit/config.toml
echo headless = true >> ~/.streamlit/config.toml
